name: overlay_search_bar_example
description: Example for overlay_search_bar
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  overlay_search_bar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true