name: overlay_search_bar
description: A highly customizable search bar widget for Flutter with overlay support.
version: 0.0.1
homepage: https://github.com/adhilkrishnag/overlay_search_bar
repository: https://github.com/adhilkrishnag/overlay_search_bar
issue_tracker: https://github.com/adhilkrishnag/overlay_search_bar/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


